In [24]:
#Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame
import pandas as pd
data = {
	'Nombre': ['Juan', 'Pedro', 'Maria', 'José', 'Anastasia', 'Ananías', 'Cupertino', 'Ramadán'],
	'Profesión': ['Ingeniero', 'Constructor', 'Doctora', 'Odontólogo', 'Psicóloga', 'Chef', 'Comerciante', 'Filósofo'],
	'Paises': ['Colombia', 'Uruguay', 'China', 'Venezuela', 'Perú', 'España', 'Francia', 'Canadá']
}
df = pd.DataFrame(data)
print(df)

      Nombre    Profesión     Paises
0       Juan    Ingeniero   Colombia
1      Pedro  Constructor    Uruguay
2      Maria      Doctora      China
3       José   Odontólogo  Venezuela
4  Anastasia    Psicóloga       Perú
5    Ananías         Chef     España
6  Cupertino  Comerciante    Francia
7    Ramadán     Filósofo     Canadá

In [15]:
#-	Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las primeras 5 filas.
import pandas as pd
df = pd.read_csv('data.csv')
print(df.head(5))

   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [16]:
#Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios,
#y luego mostrar un resumen estadístico de los datos.
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(100, 8))
print(df.describe())

                0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
mean     0.521447    0.486492    0.500954    0.462365    0.492466    0.529495
std      0.296446    0.284689    0.286485    0.291390    0.301883    0.309109
min      0.000367    0.020307    0.007550    0.017373    0.018655    0.002232
25%      0.248275    0.245111    0.288343    0.192210    0.203516    0.222914
50%      0.504353    0.467175    0.495450    0.443748    0.460176    0.550947
75%      0.787639    0.731011    0.756758    0.737564    0.767625    0.809100
max      0.999615    0.996538    0.991097    0.985005    0.990519    0.997804

                6           7
count  100.000000  100.000000
mean     0.518523    0.492010
std      0.294545    0.280105
min      0.013400    0.008625
25%      0.289234    0.276570
50%      0.508184    0.458494
75%      0.774524    0.697935
max      0.995017    0.999704

In [21]:
#Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.
import numpy as np
array = np.arange(1, 11)
print(array)
print("Suma:", np.sum(array))
print("Media:", np.mean(array))
print("Valor máximo:", np.max(array))

[ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Valor máximo: 10

In [22]:
#Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6
import numpy as np
array = np.zeros((3, 4))
print(array)
array = array.reshape(2, 6)
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

In [23]:
#Generar una matriz aleatoria de 3x3 y calcular su transpuesta
import numpy as np
array = np.random.rand(3, 3)
print(array)
print()
transpuesta = array.T
print("Matriz transpuesta:")
print(transpuesta)

[[0.53460434 0.63038989 0.14028227]
 [0.21100357 0.33895112 0.28205821]
 [0.48100748 0.03587611 0.9755788 ]]

Matriz transpuesta:
[[0.53460434 0.21100357 0.48100748]
 [0.63038989 0.33895112 0.03587611]
 [0.14028227 0.28205821 0.9755788 ]]

In [26]:
#Concatenar dos arrays de NumPy, cada uno con 5 valores,
#y luego imprimir el array concatenado
import pandas as pd
import numpy as np

a = np.array([1, 2, 3, 4, 5,])
b = np.array([6, 7, 8, 9, 10])
c = np.concatenate((a, b))
array_concatenado = np.concatenate((a, b))
print("Array concatenado:", array_concatenado)

Array concatenado: [ 1  2  3  4  5  6  7  8  9 10]